name: integration

on:
  workflow_dispatch:

jobs:
  tarantool:
    uses: ylobankov/tarantool/.github/workflows/reusable_build.yml@workflow-call
    with:
      ref: ${{ github.ref }}
      os: ubuntu
      dist: focal

  vshard:
    needs: tarantool
    uses: ylobankov/vshard/.github/workflows/reusable_testing.yml@workflow-call
    with:
      artifact_name: tarantool-ubuntu-focal-${{ github.sha }}
